export const SET_CURRENT_NOTE = 'SET_CURRENT_NOTE';
export const UPDATE_CURRENT_NOTE_TITLE = 'UPDATE_CURRENT_NOTE_TITLE';
export const UPDATE_CURRENT_NOTE_CONTENT = 'UPDATE_CURRENT_NOTE_CONTENT';
export const CLEAR_CURRENT_NOTE = 'CLEAR_CURRENT_NOTE';

// save old notes
export const SAVE_CURRENT_NOTE = 'SAVE_CURRENT_NOTE';
export const SAVE_CURRENT_NOTE_START = 'SAVE_CURRENT_NOTE_START';
export const SAVE_CURRENT_NOTE_SUCCESS = 'SAVE_CURRENT_NOTE_SUCCESS';
export const SAVE_CURRENT_NOTE_FAIL = 'SAVE_CURRENT_NOTE_FAIL';

// add new notes
export const ADD_NEW_NOTE_START = 'ADD_NEW_NOTE_START';
export const ADD_NEW_NOTE_SUCCESS = 'ADD_NEW_NOTE_SUCCESS';

// fetch all notes from server
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';

// authentication
export const SIGN_IN_STAERT = 'SIGN_IN_STAERT';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
